version: '3.3'
services:
    queries:
      container_name: queries
      image: postgres:13.5
      environment:
          - POSTGRES_USER=admin
          - POSTGRES_PASSWORD=admin
          - POSTGRES_DB=queries
          - PGDATA=/data/postgres
      volumes:
        - postgres=/data/postgres
      ports:
        - "5432:5432"